services:
  rabbitmq:
    hostname: 'rabbit'
    image: rabbitmq
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  registration:
    build:
      context: .
      dockerfile: ./apps/registration/Dockerfile
      target: production
    env_file:
      - ./apps/registration/.env
    depends_on:
      - rabbitmq
      - db
    ports:
      - '3000:3000'

  push:
    build:
      context: .
      dockerfile: ./apps/push/Dockerfile
      target: production
    env_file:
      - ./apps/push/.env
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
  rabbitmq_data:
